### PR TITLE
Add script to run CSP on all subjects

### PR DESCRIPTION
**Pull request by JD-Zhu**
WIP - a script to run CSP (should give the same results as the mne-bids-pipeline), so we can extract the CSP output for individual subjects, and then project to source space.

Hits an error at the step where the Scaler is applied:

Line 67: X = scaler.fit_transform(X, y=labels)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/decoding/transformer.py", line 215, in fit_transform
    return self.fit(epochs_data, y).transform(epochs_data)
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/decoding/transformer.py", line 162, in fit
    _sklearn_reshape_apply(self._scaler.fit, False, epochs_data, y=y)
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/decoding/transformer.py", line 66, in _sklearn_reshape_apply
    X = func(X, *args, **kwargs)
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/decoding/transformer.py", line 45, in fit
    std[picks] = 1.0 / scalings[kind]
IndexError: index 216 is out of bounds for axis 0 with size 216

### CODE REVIEW

**Comment by larsoner** [comment]
This is almost certainly an MNE bug, I should be able to look tomorrow

**Comment by larsoner** [comment]
@JD-Zhu script should work now, feel free to try it! I would start by comparing scores for one or two subjects in the bands 
and time windows of interest to see if they roughly match

**Comment by JD-Zhu** [comment]
Thanks @larsoner 
I've compared the scores from this script with the ones from the excel file generated by the mne-bids-pipeline, and they are not very similar (see example below for sub-03). Is this a concern?

Screenshot 2024-02-16 151357

**Comment by larsoner** [comment]
The scores I uploaded from the pipeline 20240206 have a bug where just EEG is used (effectively). I'm uploading new processing results that have that bug fixed and break up the window into -1, -0.5, 0, 0.5, 1 rather than -1, 0, 1. We should compare to that -- hopefully it's closer!

**Comment by JD-Zhu** [comment]
Thanks! When we do the source loc, should it also be done on the 4 time windows (ie. -1 ~ -0.5,  -0.5 ~ 0,  0 ~ 0.5,  0.5 ~ 1)?

And just to confirm if my understanding is correct - the coef from the classifier contains the channel weightings, so we create an evoked object from the coef, and then apply the inverse solution (-inv.fif) to get the source results?

**Comment by larsoner** [comment]
Yes to both!

**Comment by JD-Zhu** [comment]
Added some code to project to source space. However, when I try to plot the stc, I keep running into this error (tried on 3 subjects, all gave the same error below) - any ideas what might be the cause?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/source_estimate.py", line 743, in plot
    brain = plot_source_estimates(
  File "<decorator-gen-164>", line 12, in plot_source_estimates
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/viz/_3d.py", line 2431, in plot_source_estimates
    return _plot_stc(
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/viz/_3d.py", line 2601, in _plot_stc
    brain.setup_time_viewer(time_viewer=time_viewer, show_traces=show_traces)
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/viz/_brain/_brain.py", line 599, in setup_time_viewer
    self._configure_shortcuts()
  File "/home/jzhu/.local/lib/python3.8/site-packages/mne/viz/_brain/_brain.py", line 1217, in _configure_shortcuts
    self.plotter.clear_events_for_key(key)
  File "/home/jzhu/.local/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 1303, in clear_events_for_key
    self.iren.clear_events_for_key(key)
  File "/home/jzhu/.local/lib/python3.8/site-packages/pyvista/plotting/render_window_interactor.py", line 168, in clear_events_for_key
    self._key_press_event_callbacks.pop(key)
KeyError: 'Left'

**Comment by JD-Zhu** [comment]
I was also wondering - what does the "n_components" mean? I thought these are CSP components, but the coef (and the evoked object created from this) seem to think they only contain data at 4 time points between 0 ~ 0.015s?

**Comment by larsoner** [comment]
> However, when I try to plot the stc, I keep running into this error (tried on 3 subjects, all gave the same error below) - any ideas what might be the cause?

That's a bit odd. Maybe you need to update PyVista and/or PyVistaQt? Which versions are you on (you can check with `mne sys_info`)?

> what does the "n_components" mean?  I thought these are CSP components

Indeed they are CSP components / spatial patterns. The `coef` should be shape `(n_channels, n_components)`. In this case we're choosing to use `n_components=4`, so 4 spatial patterns to distinguish between the two states. The patterns end up as "time points" in the Evoked data but it's really a misnomer -- each "time point" is just one of the 4 spatial patterns.

**Comment by JD-Zhu** [comment]
> Maybe you need to update PyVista and/or PyVistaQt? Which versions are you on (you can check with `mne sys_info`)?

Yes that fixed it, thanks!

> The patterns end up as "time points" in the Evoked data but it's really a misnomer -- each "time point" is just one of the 4 spatial patterns.

Ah okay, that makes sense. For the 4 CSP components, do we need to source localise them separately? (i.e. each subject ends up with 4 time windows x 4 frequency bands x 4 components = 64 source results?)

**Comment by larsoner** [comment]
Yes you'd want to localize them separately.

I think in the end we want some way to quantify the contribution to weights across multiple source estimates (be they multiple components from one subject, or multiple components across multiple subjects). One option is:

1. Source localize the coef, take the absolute value, and then binarize it where perhaps the top quartile of weights have value 1 and the rest are zero. In code this would be something like `data = (np.abs(stc.data) >= np.percentile(np.abs(stc.data), 75))).astype(float)`).
2. Then for each subject you can just sum across these STCs and view the result. The STC will have discrete integer values 0, 1, 2, 3, and 4 only, indicating for a given region the number of components it was highly influential in.
3. Then across subjects you can just take the sum of *those* STCs, which will then take on (in principle) integer values between 0 and 64. In practice no area should be used in all components for all subjects so the max value will probably be much lower (maybe 10 or 20?). Plotting these tells us how many of the 64 `subj x comp` components were used.

If it's more intuitive, you could also divide the STCs in (2) by `n_components` i.e. 4, and the STCs in (3) by `n_components * n_subjects` i.e. 64 and then multiply by 100 to convert them to percentages if you want. But either way I think this will give us a good handle on the regions that are used. It's not a statistical test or anything, more like a grand average sort of thing across subjects. Probably not good enough for drawing conclusions (it's not a statistical test), but should be good enough for eye candy for a presentation!

Of course another option is just to source localize each of the 64, take the magnitude, divide by the max across the brain (to ensure scales are consistent across components and subjects), and then average across subjects. This is probably also worth plotting and shouldn't be too much on top of doing the above.

**Comment by JD-Zhu** [comment]
@larsoner Thanks for the detailed steps - it's a lot clearer now!

I'll try to make progress on this in the next couple of days, but it probably won't make it into Simon's presentation (sounds like he's quite happy with the results we have so far though!)

**Comment by JD-Zhu** [comment]
> The scores I uploaded from the pipeline 20240206 have a bug where just EEG is used (effectively). I'm uploading new processing results that have that bug fixed and break up the window into -1, -0.5, 0, 0.5, 1 rather than -1, 0, 1. We should compare to that -- hopefully it's closer!

The scores still seem quite different! (e.g. see beta band below)

sub-03

**Comment by larsoner** [comment]
Sorry for the slow response here... yes we'll have to investigate why it's different. Some minor differences in the code... or maybe even the random state (which would be bad)?

**Comment by JD-Zhu** [comment]
Do you mean the random state for the cross validation? In the current
script it's set to 42. In the mne-bids-pipeline, the default also seems to
be 42:
https://github.com/mne-tools/mne-bids-pipeline/blob/main/mne_bids_pipeline/_config.py

**Comment by larsoner** [comment]
@JD-Zhu any progress on getting these into source space? If not I can take a stab at the [idea I came up withabove](https://github.com/Macquarie-MEG-Research/natural_conversations/pull/8#issuecomment-1952878034). I still haven't figured out (or looked into much) the difference with the pipeline but we'll want the source space viz either way I think.

**Comment by JD-Zhu** [comment]
@larsoner Sorry for the slow progress - I have been unwell and taking time
off work. If you would like to take a look at this, that would be great. My
latest code update was in the last push. Apologies again and I'll try to
get back on board asap.

**Comment by JD-Zhu** [comment]
@larsoner I plan to spend some time this week on the source localisation of the CSP results. Was just wondering if you made any new changes to the code since my last commit? (just so we don't end up diverging) Thanks :)

**Comment by larsoner** [comment]
Yes pushing some updates soon -- with the updated script I get for 03 for example

| | script | pipeline |
| -- | -- | -- |
| alpha -1.0 - -0.5s | 0.70 | 0.67 |
| alpha -0.5 - 0.0s | 0.72 | 0.66 |
| alpha 0.0 - 0.5s | 0.68 | 0.78 |
| alpha 0.5 - 1.0s | 0.62 | 0.65 |
| beta  -1.0 - -0.5s | 0.97 | 0.99 |
| beta  -0.5 - 0.0s | 0.99 | 0.96 |
| beta  0.0 - 0.5s | 0.97 | 0.95 |
| beta  0.5 - 1.0s | 0.92 | 0.96 |

The difference I think was `whiten=True`, which is useful to have. From a quick look at the 5 CV splits, the differences in the means are now within a reasonable range given the CV splits (e.g., for `|alpha -1.0 - -0.5s: 0.70 | 0.67 |` the CV values in the spreadsheet are `[0.61458333 0.53125    0.70454545 0.67857143 0.82142857]`

**Comment by larsoner** [comment]
Okay pushed, hopefully at your end you can reproduce the images at the bottom of our Google Doc that I generated!

**Comment by JD-Zhu** [comment]
> Yes pushing some updates soon -- with the updated script I get for 03 for example
> 
> script	pipeline
> alpha -1.0 - -0.5s	0.70	0.67
> alpha -0.5 - 0.0s	0.72	0.66
> alpha 0.0 - 0.5s	0.68	0.78
> alpha 0.5 - 1.0s	0.62	0.65
> beta -1.0 - -0.5s	0.97	0.99
> beta -0.5 - 0.0s	0.99	0.96
> beta 0.0 - 0.5s	0.97	0.95
> beta 0.5 - 1.0s	0.92	0.96
> The difference I think was `whiten=True`, which is useful to have. From a quick look at the 5 CV splits, the differences in the means are now within a reasonable range given the CV splits (e.g., for `|alpha -1.0 - -0.5s: 0.70 | 0.67 |` the CV values in the spreadsheet are `[0.61458333 0.53125 0.70454545 0.67857143 0.82142857]`

Awesome - thanks for looking into this!

**Comment by JD-Zhu** [comment]
> Okay pushed, hopefully at your end you can reproduce the images at the bottom of our Google Doc that I generated!

Thanks! I'll run on my end and report back tomorrow :)

**Comment by JD-Zhu** [comment]
I kept having issues with the plotting yesterday but it seems to have fixed itself today! Can confirm I've got the same figure :)

**Comment by JD-Zhu** [comment]
@larsoner Hope you are well! I am working on verifying the reduction of source amplitudes after motor artifact removal with SSP. Would you be able to push the code for generating the SSP projectors or alternatively upload the -epo files following motor artifact removal? Thanks!

**Comment by larsoner** [comment]
Yes sorry I meant to push earlier, done!

**Comment by larsoner** [comment]
@JD-Zhu I saw the boolean switch you added to `bidsify.py`, `config.py`, and `csp.py`, but the problem is that it requires setting it in three places and you end up with different files for analysis that way. In https://github.com/Macquarie-MEG-Research/natural_conversations/pull/8/commits/fe355d97542f673665672affc8413a7fd41be64d I pushed a change that unifies everything by always adding the events, then you can choose in `csp.py` or whereever which conditions you actually want to analyze.

I also put back the `exclude_subjects` stuff since it's working at my end -- if it doesn't for you, we should debug and fix it! It could be a bug in mne-bids-pipeline worth fixing for example.

I suggest we merge this PR next so that the diff doesn't grow too much and then proceed with smaller more targeted PRs, WDYT?

**Comment by JD-Zhu** [comment]
Thanks @larsoner - I think this is a much better solution!

And sure, I'll let you know if I run into any further issues with the "exclude_subjects" part.

Happy to merge this PR whenever you are ready :)

**Comment by larsoner** [comment]
Okay let's merge and iterate from here!

**Pull request merged**
