### PR TITLE
ENH: add speech timestamps to _events.tsv file

### PR DESCRIPTION
**Pull request by larsoner**
Turning this into a PR so we can see the diff easily @JD-Zhu !

### CODE REVIEW

**Comment by larsoner** [comment]
@JD-Zhu short version here is that if you do `raw.set_annotations(...)` on a file before calling `write_raw_bids`, it automatically converts annotations to events and puts them in `_events.tsv`. Can you check this file that I generated on 5e12441 against one you generated to make sure they match? Had to rename the extension to make GitHub happy with the upload:

[sub-01_task-conversation_run-01_events.txt](https://github.com/Macquarie-MEG-Research/natural_conversations/files/14169189/sub-01_task-conversation_run-01_events.txt)

**Comment by JD-Zhu** [comment]
> @JD-Zhu short version here is that if you do `raw.set_annotations(...)` on a file before calling `write_raw_bids`, it automatically converts annotations to events and puts them in `_events.tsv`. Can you check this file that I generated on [5e12441](https://github.com/Macquarie-MEG-Research/natural_conversations/commit/5e1244192bc85819eff360221fb395e61d3ce1da) against one you generated to make sure they match? Had to rename the extension to make GitHub happy with the upload:
> 
> [sub-01_task-conversation_run-01_events.txt](https://github.com/Macquarie-MEG-Research/natural_conversations/files/14169189/sub-01_task-conversation_run-01_events.txt)

Yep I have checked this events file and it matches the one I generated.

**Comment by JD-Zhu** [comment]
@larsoner Should we merge this PR?

**Comment by larsoner** [comment]
Yes if you're happy feel free and we can keep iterating in future PRs

**Pull request merged**
